# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gecoa', '0002_auto_20171013_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.Attachment'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.Photo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='gecoa.Province'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.Technology'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.ExperienceType'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='gecoa.Province'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.Photo'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='gecoa.TechnologyType'),
        ),
    ]
